INSERT INTO category (description) VALUES ('American')
INSERT INTO category (description) VALUES ('Italian')
INSERT INTO category (description) VALUES ('Mexican')
INSERT INTO category (description) VALUES ('Fast Food')
INSERT INTO unit_of_measure (uomdescription) VALUES ('Teaspoon')
INSERT INTO unit_of_measure (uomdescription) VALUES ('Tablespoon')
INSERT INTO unit_of_measure (uomdescription) VALUES ('Cup')
INSERT INTO unit_of_measure (uomdescription) VALUES ('Pinch')
INSERT INTO unit_of_measure (uomdescription) VALUES ('Ounce')